<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="expires" content="-1" />
	<title>$title$ | Sample Site</title>
	<link rel="stylesheet" type="text/css" href="/Content/css/style.css" ></link>
	

</head>

<body><center>
	<div id="Granny">
		<div id="HeaderCont"><div id="HeaderInn">
			<div class="Clearer"></div>
			<div id="HeaderTitle">
				$title$
			</div>
			<div id="HeaderSubTitle">
				Strapline goes here...
			</div>
			<div class="Clearer"></div>
		</div></div>
		<div id="MainAndSides">
		<!-- ==================== Main Column ==================== -->
		<div id="MainCol">
			<div id="MainColInner">
				
			</div>
		</div>

		<!-- =================== Side L Column =================== -->
		<div id="SideLCol" class="SideBar">
			<div class="SideBarInner">
				<div class="Box">
					<div class="Inner">
						<a href="/Sample/Home/index" title="First Page">Home</a><br />
					</div>
				</div>
				<div class="Clearer"></div>
			</div>
		</div>

		<div class="Clearer"></div>
		</div>

		<div id="ColClose"></div>
		<div id="CopyRight">
			The <a target="_self" href="javascript: void(0);" onclick="javascript:MyPsycHicForm.submit();">Template</a> is generated via <a href="http://psyc.horm.org">PsycHo</a> and is <a href="http://creativecommons.org/licenses/by-nc/2.5/">Licensed</a>. <br />
		</div>
	</div>
</center></body>
</html>
