$Sample/shared/master(
	title= {Lunch Menu},
	content={
		<div>
			$Sample/shared/menuitem(title = {Citrus-baked Mackerel}, description={ Fresh mackerel selected by our head chef every morning from Billingsgate market, served on a bed of aromatic couscous with a side salad}, price={7.50})$
			$Sample/shared/menuitem(title = {Lasagne Verdi}, description={ An individually baked spinach pasta lasagne served with warm crusty bread and a side salad. Vegetarian option available on request. }, price={6.50})$
			$Sample/shared/menuitem(title = {Poached Salmon and New Potatoes}, description={ A tender poached salmon fillet served with butter-garnished Jersey Royals and fresh garden peas. }, price={6.50})$
			<h2>Something for afterwards</h2>
			$Sample/shared/menuitem(title = {Cheese Platter}, description={ A selection of British and Continental cheeses, served with fresh crusty bread and our home made chutney. }, price={5.50})$
			$Sample/shared/menuitem(title = {Grandma's Chocolate cake}, description={ A layered chocolate sponge cake with buttercream icing. Served with fresh cream. }, price={4.50})$
			$Sample/shared/menuitem(title = {Raspberry Meringue}, description={ Fresh raspberries served with a crunchy meringue and cream.}, price={4.50})$
		</div>	
	}
)$